project:
  type: website

website:
  title: "STAT 541 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - portfolio.qmd

format:
  html:
    # TODO: add dark theme
    theme: lux 
    css: styles.css
    toc: true

execute:
  freeze: auto
