name: Render and Deploy Quarto Project to Cloudflare Pages

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    env:
      DASHBOARD_REPO_OWNER: VisruthSK
      DASHBOARD_REPO_NAME: lab-3
      RENV_PATHS_ROOT: ~/.cache/R/renv
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Setup renv
        uses: r-lib/actions/setup-renv@v2

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html

      - name: Check out dashboard
        uses: actions/checkout@v4
        with:
          repository: ${{ env.DASHBOARD_REPO_OWNER }}/${{ env.DASHBOARD_REPO_NAME }}
          path: dashboard_content
          depth: 1        

      - name: Copy Dashboard HTML
        run: |
          cp "dashboard_content/dashboard.html" "_site/static_dashboard.html"
        shell: bash

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'stat-541'
          directory: '_site'