name: Render and Deploy Quarto Project to Cloudflare Pages

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    env:
      R_LIBS_USER: "/tmp/null"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: latest

      - name: Setup R, renv, and cache packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          r-version: 'release'
          cache-version: 1

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'stat-541'
          directory: '_site'